.TH "C0KS" 1 "24/02/2017" "C0ks" "C0KS Reference Guide"
.SH NAME
c0ks - Chief's Zero Knowledge Storage
.SH SYNOPSIS
For a detailed description of options and actions see respectively chapters \fBOPTIONS\fR and \fBACTIONS\fR.
.PP
\fBc0ks\fR [\fIoptions\fR] \fIaction\fR
.SH DESCRIPTION
\fBC0KS\fR stands for Chief's Zero Knowledge Storage. It was born out of a necessity to give users of online file hosting services a chance to be in control of their data in \(lqthe cloud\(rq.
.PP
In essence it is a simple duplicity wrapper with a couple of extra features. Duplicity works by taking backups of a directory: each backup is split up into volumes (each of max 200M), which are signed and encrypted using GnuPG and then uploaded to a specified remote.
Duplicity uses the rsync utility, which enables is to only process and send those parts of files that have changed since the last backup. This minimizes the traffic and space usage.
What is stored in the remote are only encrypted tarballs of the data (for full backups) or encrypted tar archives of the new files and deltas of old backups (for incremental backups)
.PP
The use of encryption ensures that the remote location cannot know anything about what is being uploaded and hosted, except for the size of the volumes and when they are uploaded. Hence the zero knowledge part of the name C0KS.
Moreover, before being encrypted the volumes are signed with the user's private PGP key, which makes sure that when he later accesses his data he can be sure it was not tampered with, by checking the cryptographic signature.
.PP
C0KS adds to Duplicity a \fIdiff feature\fR, which enables the user to clearly visualize the differences between the remote and local data, without having to download and process it all: it notifies about new local files absent in the remote and viceversa, as well as changes to local or remote files.
The user can then decide what to do, namely synchronizing the remote with the local storage or pulling the more recent data from the remote to the local storage.
.SH OPTIONS
\fB-c\fR (No Colors)
.RS 4
Disable colors in the output.
.RE
.PP
\fB-h\fR (Show Help)
.RS 4
Print a help message, useful for a quick reminder of the available options and actions.
.RE 
.PP
\fB-L\fR \fIfile\fR (Specify Log File)
.RS 4
Use \fIfile\fR as log file for C0KS.
.RE 
.PP
\fB-n\fR (Dry Run)
.RS 4
Run the program without performing any action, but merely simulating what would be done. This is most useful combined with the \fB-v\fR option to enable verbose output.
.RE 
.PP
\fB-v\fR (Verbose Output)
.RS 4
Enable verbose output. This also makes duplicity more verbose, which can make the output quite noisy.
.RE 
.PP
\fB-w\fR \fIdir\fR (Specify Local Target Directory)
.RS 4
Sets \fIdir\fR as the local directory where the data is locally stored. 
.\" write a notice about what happens if the user changes this after already having a working setup.
.RE 
.SH ACTIONS
\fBpush\fR
.RS 4
On the first run, \fBpush\fR creates a new full backup of the specified local directory. On subsequent runs incremental backups are performed.
If a file was modified locally its changes will be uploaded. If a file that was in the remote was locally deleted it will be deleted in the remote as well. If a new file was created locally it will be uploaded to the remote (after being processed, encrypted and signed).
.PP
When done print a summary of what has been done.
.RE
.PP
\fBpull\fR
.RS 4
Replace the contents of the local storage with that of the remote, downloading (decrypting and verifying) the data to the local storage directory.
Note that at the moment it is not possible to simply pull the files that are new or updated on the remote and place them in the local storage directory. Only a full restore of the remote to the local storage is supported for now.
Implementation of partial restores has already been planned.
.RE
.PP
\fBstatus\fR
.RS 4
Show some information about the remote such as: date and time of first and last backups, number of backups performed, number of contained volumes, as well as a table of backup sets. 
.RE
.PP
\fBdiff\fR
.RS 4
Show delta of remote and local storage, without downloading the whole backup. The output highlights: new local files to be uploaded to remote, new remote files to be pulled to the local storage directory, files that changed on the remote and files that changed in the local storage.
.RE
.PP
.SH CONFIGURATION
Options and actions should be satisfactory for everyday usage of C0KS. Nonetheless the program should be configured carefully before running it, to obtain the desired results. 
Parameters that require configuration are at least: address and password of the remote, encryption and signing keys, local storage directory. Other parameters may be configured as well. 
.PP
Parameters are configured by directly changing their values in the source of the script. 
.PP
\fBENCRYPT_KEY\fR 
.RS 4
ID or fingerprint of the GnuPG key to be used to encrypt files in the remote.
.RE
.PP
\fBSIGN_KEY\fR 
.RS 4
ID or fingerprint of the GnuPG key to be used to sign files in the remote (can be equal to ENCRYPT_KEY)
.RE
.PP
\fBGPG_AGENT_CACHE_DURATION\fR 
.RS 4
Determines maximum duration of a push action. Defaults to 1 week.
.RE
.PP
\fBREMOTE_ADDR\fR 
.RS 4
The address of the remote, using the appropriate protocol (ftp, webdav, ecc) using the syntax [protocol]://[user]@[server]
.PP
e.g. If Sharon used box.com as a remote storage provider (which supports the webdav protocol) and she was registered with the email address sharon.valerii@galactica.com she would have to set something like:
.RS 6
\fBREMOTE_ADDR="webdavs://sharon.valerii@galactica.com@dav.box.com/dav/c0ks"\fR
.RE
.PP
e.g. If Sharon used her account sharon.valerii at the cylon server for ftp and her path there was /baseship/boomer she would have to set something like:
.RS 6
\fBREMOTE_ADDR="sftp://sharon.valerii@cylon.com/baseship/boomer"\fR
.RE
.PP
Duplicity currently supports the following solutions as remotes: local file storage, scp/ssh, ftp, rsync, HSI, WebDAV, Tahoe-LAFS, and Amazon S3.
For details on how to specify the REMOTE_ADDR in cases not covered here, refer to the Duplicity documentation.
.RE
.PP
\fBPASS_ENTRY\fR
.RS 4
If the password manager utility \fIpass\fR is installed and you have an entry in \fIpass\fR for the remote you are going to use (ftp server, webdav account, etc.) set this variable to the name of the \fIpass\fR entry. e.g. If
.RS 6
\fB# pass show c0ks_remote\fR
.RE
shows the password to your remote, set this variable to \fIc0ks_remote\fR.
.RE
.PP
\fBLOG_FILE\fR 
.RS 4
Where you want to save the session log file. Set to \fB/dev/null\fR if you don't want logs.
.RE
.PP
\fBSTORAGE_NAME\fR 
.RS 4
A name for your C0KS. This acts as an identifier for your set of backups.
.RE
.PP
\fBDUPLICITY_LOG_FD\fR 
.RS 4
Used to redirect output between stdout and log file. Do NOT change this, unless you know what you are doing.
.RE
.PP
\fBDUPLICITY_OPTIONS\fR 
.RS 4
Specify some sensible Duplicity options. Do NOT change this, unless you know what you are doing.
.RE
.PP
\fBLOCAL_TARGET_DIR\fR
.RS 4
Path of the directory where you want to store the local copy of the data.
This can also be specified with the \fB-w\fR option.
.RE
.PP
\fBEXCLUDE\fR
.RS 4
List here optional subdirs of \fBLOCAL_TARGET_DIR\fR that you don't want included in the backups. Each entry should be preceded by --exclude.
.RS 6
e.g. \fBEXCLUDE="--exclude ${LOCAL_TARGET_DIR}/useless_stuff --exclude ${LOCAL_TARGET_DIR}/unnecessary_dir"\fR
.RE
.RE
.SH A NOTE ON PASSWORDS
C0KS makes use of two distinct passwords: the one to access the remote storage and the one to unlock the GnuPG private key.
The latter should be asked by the \fIgpg-agent\fR pinentry utility or directly by Duplicity when needed. Since \fBpush\fR actions can take a long time to complete (for large full backups), a new gpg-agent instance is started when c0ks is run and is closed when c0ks exits. The maximum time the \fIgpg-agent\fR daemon will be kept running is \fBGPG_AGENT_CACHE_DURATION\fR and defaults to a week.
.PP
The password to the remote storage can be specified in two ways: if you use the password manager \fIpass\fR by setting the configuration variable \fBPASS_ENTRY\fR; otherwise you can specify the password by setting the environment variable \fBC0KS_PASSWORD\fR when launching c0ks. e.g.
.RS 4
\fB# C0KS_PASSWORD="itsinthefrakkingship" c0ks push\fR
.RE
.SH NOTICE
C0KS's author is not responsible for any data loss or damage to your system. Even though highly unlikely to happen, keep in mind this project is still in its testing phase.
For more advanced operations on the storage, such as restoring specific backup or deleting backups you should use Duplicity directly.
In passing, I thank Duplicity and its community for working at such a wonderful project which inspired me to write this little tool.
.SH AUTHOR
chftyrol <chftyrol@mailfence.com>
